#!/usr/bin/env python3
"""Build the Obsidian view of the launch plan from docs/team-plan.json.

Writes, under docs/plan/:
  tasks/        one note per task, linked to dependencies, owner and checkpoint
  owners/       one hub note per vertical or role
  checkpoints/  one note per checkpoint, chained in order
  roomsie launch.md       the centre of the graph, with a legend
  Launch timeline.canvas  swimlanes by owner, laid out on a calendar
and .obsidian/graph.json with colours by owner.

Generated. Edit docs/team-plan.json, then run: python3 tools/build-obsidian-plan.py
GitHub issues stay the live tracker.
"""
import json, os, shutil, datetime as dt

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAN = os.path.join(ROOT, "docs", "plan")
P = json.load(open(os.path.join(ROOT, "docs", "team-plan.json")))
T = P["tasks"]
REPO = "https://github.com/magentawood/roomsie/issues/"

SHORT = {
 "T-02":"Scaffold monorepo","T-05":"Google sign-in","T-04":"Deploy to Mumbai","T-03":"CI checks",
 "T-07":"Error reporting","T-33":"Invite-only gate","T-24":"Event logging","T-23b":"Legal pages",
 "T-25":"Uptime and spend alerts","T-29":"Abuse test","T-08":"Form A contract","T-11":"Model wrapper",
 "T-12":"Extraction","T-13":"Reply writer","T-21":"Turn cap and spend ceiling","T-27":"Eval run",
 "T-10":"Chat screen and split view","T-09":"Chip flow","T-17":"Carry chat into account",
 "T-23a":"Landing page","T-22":"Launch areas and waitlist","T-06":"Database schema","T-14":"Match query",
 "T-19":"Report and block","T-20":"Account deletion","T-18b":"Person and connect screens",
 "T-15":"Results panel","T-16":"Profiles and photos","T-18a":"Connect API",
 "D-01":"Styling decision","D-02":"Chat screen designs","D-03":"Results and profile designs",
 "D-04":"Landing and waitlist designs","D-05":"Design QA","D-06":"Launch visuals",
 "M-04":"Article interviews","M-03":"Eval sentences","M-05":"Article drafts","M-07":"Launch posts",
 "M-01":"Seeding form","M-02":"100 sign-ups","M-06":"Beta invites","M-09":"Broker calls",
 "F-01":"Kickoff","F-02":"Domain","F-03":"Billing and caps","F-04":"Accounts in Mumbai",
 "F-05":"Seeding consent text","F-06":"Launch areas picked","F-07":"Privacy and terms draft",
 "F-09":"ADR exceptions","F-08":"Moderator named","F-10":"Go-no-go meeting",
 "A-01":"Bug fix day","A-02":"Launch day",
}
OWNERS = [  # key, note name, tag, colour
 ("V1","V1 Platform","v1","#8B949E"),
 ("V2","V2 Assistant","v2","#8B6CFF"),
 ("V3","V3 Visitor journey","v3","#3B82F6"),
 ("V4","V4 Matching and trust","v4","#2EA44F"),
 ("V5","V5 People and connections","v5","#14B8A6"),
 ("D","Design","design","#FF87AC"),
 ("M1","M1 Content","content","#E3B341"),
 ("M2","M2 Community","community","#F9A03F"),
 ("F","Founder","founder","#B07B4F"),
 ("ALL","Everyone","everyone","#9CC3E6"),
]
OWN = {k:(n,tag,c) for k,n,tag,c in OWNERS}
QUESTION = {"V1":"The ground everyone builds on","V2":"What the assistant understands and says",
 "V3":"From landing to signed in","V4":"Who sees whom","V5":"The people on the screen"}
CPNAME = {"CP0":"CP0 Kickoff","CP1":"CP1 Foundation","CP2":"CP2 Core loop live",
 "CP3":"CP3 Freeze and go-no-go","CP4":"CP4 Launch","CP5":"CP5 First-week review"}
CPCOLOUR = "#D73A4A"
SOFT = {"T-18b":("T-18a","Wire to it when it lands on Sun 4 Oct"),
        "T-15":("T-14","Wire to it when it lands on Wed 30 Sep")}

D = dt.date.fromisoformat
f = lambda s: D(s).strftime("%a %-d %b")
by = {t["id"]:t for t in T}
def name(tid):
    t = by[tid]; return f"{tid} {SHORT[tid]}" + (" ⚑" if t["critical"] else "")
def link(tid): return f"[[{name(tid)}]]"
def rel(path):  # repo path -> link from docs/plan/<sub>/
    p = path[5:] if path.startswith("docs/") else "../" + path
    return "../../" + p
unblocks = {t["id"]:[] for t in T}
for t in T:
    for d in t["deps"]: unblocks[d].append(t["id"])
    if t["id"] in SOFT: unblocks[SOFT[t["id"]][0]].append(t["id"])
seq = {}
for k in OWN:
    rows = sorted([t for t in T if t["role"]==k], key=lambda t:(t["start"],t["end"],t["id"]))
    for i,t in enumerate(rows,1): seq[t["id"]] = (i,len(rows))

for sub in ("tasks","owners","checkpoints"):
    shutil.rmtree(os.path.join(PLAN,sub), ignore_errors=True)
    os.makedirs(os.path.join(PLAN,sub))
def write(sub, fname, text):
    with open(os.path.join(PLAN, sub, fname) if sub else os.path.join(PLAN, fname), "w") as fh: fh.write(text)

HEADER = "<!-- Generated by tools/build-obsidian-plan.py. Edit docs/team-plan.json instead. -->\n"

# task notes
for t in T:
    own, tag, _ = OWN[t["role"]]
    i, n = seq[t["id"]]
    when = f(t["start"]) if t["start"]==t["end"] else f"{f(t['start'])} → {f(t['end'])}"
    tags = ["task", tag] + (["critical"] if t["critical"] else [])
    fm = ["---", f"id: {t['id']}", f"title: \"{t['title']}\"", f"owner: \"{own}\"",
          f"sequence: \"{i} of {n}\""]
    if t["hours"]: fm.append(f"hours: {t['hours']}")
    fm += [f"start: {t['start']}", f"end: {t['end']}", f"checkpoint: {t['cp']}",
           f"critical: {'true' if t['critical'] else 'false'}", f"issue: {REPO}{t['issue']}",
           "tags:"] + [f"  - {x}" for x in tags] + ["---"]
    b = fm + [HEADER, f"# {t['id']} · {t['title']}\n",
          f"**Owner:** [[{own}]], task {i} of {n}  ",
          f"**When:** {when}" + (f" · {t['hours']} hours" if t["hours"] else "") + "  ",
          f"**Checkpoint:** [[{CPNAME[t['cp']]}]]  ",
          f"**Issue:** [#{t['issue']}]({REPO}{t['issue']})"]
    if t["critical"]: b.append("\n> [!warning] Critical path\n> If this slips, the launch slips.")
    b.append("\n## Needs first")
    b += [f"- {link(d)}" for d in t["deps"]] or ["- Nothing. Start any time."]
    if t["id"] in SOFT:
        s, why = SOFT[t["id"]]; b.append(f"- {link(s)}, later. {why}.")
    b.append("\n## Unblocks")
    b += [f"- {link(u)}" for u in unblocks[t["id"]]] or ["- Nothing waits on this."]
    b.append("\n## Done when"); b += [f"- [ ] {d}" for d in t["done"]]
    if t["read"]:
        b.append("\n## Read first"); b += [f"- [{os.path.basename(r)}]({rel(r)})" for r in t["read"]]
    write("tasks", name(t["id"]) + ".md", "\n".join(b) + "\n")

# owner hubs
for k,(own,tag,colour) in OWN.items():
    rows = sorted([t for t in T if t["role"]==k], key=lambda t:(t["start"],t["end"],t["id"]))
    hrs = sum(t["hours"] or 0 for t in rows)
    b = ["---","tags:","  - owner",f"  - {tag}","---",HEADER,f"# {own}\n"]
    if k in QUESTION: b.append(f"_{QUESTION[k]}._\n")
    if hrs: b.append(f"**{hrs} hours** of build work, {24-hrs} spare, finishing {f(max(t['end'] for t in rows))}.\n")
    b.append("Part of [[roomsie launch]].\n\n## Sequence\n")
    for i,t in enumerate(rows,1):
        when = f(t["start"]) if t["start"]==t["end"] else f"{f(t['start'])} → {f(t['end'])}"
        b.append(f"{i}. {link(t['id'])} — {when}" + (f", {t['hours']}h" if t["hours"] else ""))
    write("owners", own + ".md", "\n".join(b) + "\n")

# checkpoints, chained
ms = P["milestones"]
for idx,(cp,label,due,what) in enumerate(ms):
    rows = sorted([t for t in T if t["cp"]==cp], key=lambda t:(t["end"],t["id"]))
    b = ["---","tags:","  - checkpoint","---",HEADER,f"# {cp} · {label}\n",f"**Date:** {f(due)}\n",what+"\n"]
    if idx: b.append(f"**After:** [[{CPNAME[ms[idx-1][0]]}]]  ")
    if idx < len(ms)-1: b.append(f"**Next:** [[{CPNAME[ms[idx+1][0]]}]]\n")
    b.append("Part of [[roomsie launch]].\n\n## Due by this checkpoint\n")
    b += [f"- {link(t['id'])} — {OWN[t['role']][0]}" for t in rows]
    write("checkpoints", CPNAME[cp] + ".md", "\n".join(b) + "\n")

# centre note with legend
leg = "\n".join(f"| <span style=\"color:{c}\">●</span> | [[{n}]] |" for _,n,_,c in OWNERS)
write(None, "roomsie launch.md", f"""---
tags:
  - checkpoint
---
{HEADER}
# roomsie launch

Target **Wed 7 Oct 2026**, fallback Fri 9 Oct. {len(T)} tasks.

## How to look at it

- **Graph view.** Open it with Cmd+G. It shows only this plan, coloured by owner. Every line is a link: a task to what it waits on, to its owner, and to its checkpoint. ⚑ marks the critical path.
- **Timeline.** Open [[Launch timeline.canvas]]. One swimlane per person, laid out on the calendar. Red cards are the critical path, and arrows show what waits on what.
- **One person's view.** Open their owner note and turn on the local graph.

## Owners

| Colour | Owner |
|---|---|
{leg}
| <span style="color:{CPCOLOUR}">●</span> | Checkpoints |

## Checkpoints

""" + "\n".join(f"- [[{CPNAME[cp]}]] — {f(due)}" for cp,_,due,_ in ms) + """

---

These notes are generated from `docs/team-plan.json`. To change the plan, edit that file and run `python3 tools/build-obsidian-plan.py`. The [GitHub issues](https://github.com/magentawood/roomsie/issues) stay the live tracker.
""")

# canvas: swimlanes on a calendar
day0 = D("2026-09-24"); days = (D("2026-10-14")-day0).days + 1
W, H, GAP, PAD = 220, 84, 12, 30
nodes, edges = [], []
for i in range(days):
    d = day0 + dt.timedelta(i)
    nodes.append(dict(id=f"day{i}", type="text", text=f"**{d.strftime('%a')}**\n{d.strftime('%-d %b')}",
        x=i*W, y=0, width=W-8, height=60, **({"color":"#6E7781"} if d.weekday()>=5 else {})))
for cp,label,due,_ in ms:
    i = (D(due)-day0).days
    nodes.append(dict(id=f"cp-{cp}", type="text", text=f"**{cp}**\n[[{CPNAME[cp]}|{label}]]",
        x=i*W, y=72, width=W-8, height=80, color=CPCOLOUR))
y = 200
for k,(own,tag,colour) in OWN.items():
    rows = sorted([t for t in T if t["role"]==k], key=lambda t:(t["start"],t["end"],t["id"]))
    lanes = []   # pack overlapping tasks into sub-rows
    place = {}
    for t in rows:
        s, e = (D(t["start"])-day0).days, (D(t["end"])-day0).days
        for li, last in enumerate(lanes):
            if s > last: lanes[li] = e; place[t["id"]] = li; break
        else: lanes.append(e); place[t["id"]] = len(lanes)-1
    height = PAD*2 + len(lanes)*(H+GAP) - GAP
    nodes.append(dict(id=f"lane-{k}", type="group", label=own, x=-20, y=y, width=days*W+32, height=height, color=colour))
    for t in rows:
        s, e = (D(t["start"])-day0).days, (D(t["end"])-day0).days
        info = (f"{t['hours']}h · " if t["hours"] else "") + (f(t["start"]) if s==e else f"{f(t['start'])} → {f(t['end'])}")
        n = dict(id=f"task-{t['id']}", type="text", text=f"**[[{name(t['id'])}|{t['id']} {SHORT[t['id']]}]]**\n{info}",
                 x=s*W, y=y+PAD+place[t["id"]]*(H+GAP), width=(e-s+1)*W-8, height=H)
        if t["critical"]: n["color"] = "1"
        nodes.append(n)
    y += height + 50
for t in T:
    for d in t["deps"]:
        e = dict(id=f"e-{d}-{t['id']}", fromNode=f"task-{d}", fromSide="right", toNode=f"task-{t['id']}", toSide="left")
        if t["critical"] and by[d]["critical"]: e["color"] = "1"
        edges.append(e)
    if t["id"] in SOFT:
        s,_ = SOFT[t["id"]]
        edges.append(dict(id=f"e-{s}-{t['id']}", fromNode=f"task-{s}", fromSide="bottom", toNode=f"task-{t['id']}", toSide="bottom", label="wire up"))
json.dump(dict(nodes=nodes, edges=edges), open(os.path.join(PLAN, "Launch timeline.canvas"), "w"), indent=1, ensure_ascii=False)

# graph colours, keeping any other settings already there
gp = os.path.join(ROOT, ".obsidian", "graph.json")
os.makedirs(os.path.dirname(gp), exist_ok=True)
g = json.load(open(gp)) if os.path.exists(gp) else {}
rgb = lambda h: int(h.lstrip("#"), 16)
g.update({
 "search": "path:docs/plan",
 "showTags": False, "showAttachments": False, "hideUnresolved": True, "showOrphans": False,
 "showArrow": True, "collapse-color-groups": False,
 "colorGroups": [{"query":"tag:#checkpoint","color":{"a":1,"rgb":rgb(CPCOLOUR)}}] +
   [{"query":f"tag:#{tag}","color":{"a":1,"rgb":rgb(c)}} for _,_,tag,c in OWNERS],
})
g.setdefault("linkDistance", 180); g.setdefault("repelStrength", 12); g.setdefault("textFadeMultiplier", -0.5)
json.dump(g, open(gp, "w"), indent=2)

print(f"{len(T)} task notes, {len(OWN)} owner notes, {len(ms)} checkpoints, "
      f"canvas with {len(nodes)} nodes and {len(edges)} edges, graph colours set")
